# -*- coding: utf-8 -*-
"""Phase 2 code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ZhUV7YJ7YgM7hZT8dt3_gmM4HWuZMwy
"""

from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
chatbot=ChatBot('corona bot')
trainer = ChatterBotCorpusTrainer(chatbot)
trainer.train("chatterbot.corpus.english.greetings",
			"chatterbot.corpus.english.conversations" )

response = chatbot.get_response('What is your Number')
print(response)

response = chatbot.get_response('Who are you?')
print(response)